export const CONFIG = {
  AUHOR_NAME_LENGTH_MIN: 3,
  AUHOR_NAME_LENGTH_MAX: 30,
  CHAPTER_TITLE_LENGTH_MIN: 6,
  CHAPTER_TITLE_LENGTH_MAX: 60,
  FILE_NAME_LENGTH_MIN: 6,
  FILE_NAME_LENGTH_MAX: 60,
  FIRST_CHAPTER_ID: 'FIRST_CHAPTER_ID',
}